### ISSUE TITLE
asf.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [Duet3D/RRFLibraries#1]
Hello,

I've been trying to compile RRF for Duet2 and followed the Build instructions religiously. CoreNG builds fine, so does FreeRTOS, but when I go to build RRFLibraries, I'm getting this error:

eclipse-workspace/Firmware/FreeRTOS/src/include/FreeRTOSConfig.h:37:10: fatal error: asf.h: No such file or directory

I've tries manually including CoreNG/asf/ but that created more problems.

So far I've done this on macOS, and Windows with exactly same results.

Any guidance?

**Comment by dc42** [comment]
I'm sorry about that, I've just checked in a change to FreeRTOSConfig.h to allow RRFLibraries to build.

**Comment by tobbelobb** [comment]
I also had this problem today. On chrishamm branch of FreeRTOS, I see these two commits:
First, a fix like dc42 describes.
https://github.com/dc42/FreeRTOS/commit/51f681642f13b43f4f13345cd2ffba4ad3e72612
Then the fix is reverted by chrishamm:
https://github.com/dc42/FreeRTOS/commit/f3f5c6fc2e0526cd4b5bfd6d5f773ca96b54f90c

It looks like chrishamm was fixing something else regarding the include paths, and removed dc42's fix to this issue by accident.

I successfully included everything I needed by hand. In Properties->C/C++ Build->Settings->Cross G++ Compiler->Includes, add the paths:
```
"${workspace_loc:/CoreNG/asf/sam/drivers}"
"${workspace_loc:/CoreNG/variants/duetNG}"
"${workspace_loc:/CoreNG/asf/thirdparty/CMSIS/Include}"
"${workspace_loc:/CoreNG/asf/sam/utils/cmsis/sam4e/include}"
"${workspace_loc:/CoreNG/asf/sam/utils/header_files}"
"${workspace_loc:/CoreNG/asf/common/utils}"
"${workspace_loc:/CoreNG/asf/sam/utils}"
"${workspace_loc:/CoreNG/asf/sam/utils/preprocessor}"
"${workspace_loc:/CoreNG/asf}"
```
I guess the exact list will vary if you're not building for SAM4E and RTOS, just wanted to point out that it's possible.

**Comment by dc42** [comment]
I think I may have made a further change to the FreeRTOS project that I forgot to commit. I will check when I am back in the office.
